#!/bin/sh
# Ensure commit message is Conventional Commit.

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo "Your commit message is not Conventional Commit." >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "Your commit message is too long." >&2
  exit 1
fi
