#!/usr/bin/env bash
# Ensure Git tag is present.

set -e

GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo '')
if [[ -z "$GIT_TAG" ]]; then
  echo "ERROR: Git Tag must be set." >&2
  exit 1
fi
